# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  sistemadecadastroapi:
    image: sistemadecadastroapi
    build:
      context: .
      dockerfile: SistemaDeCadastroAPI/Dockerfile
    ports:
      - 8089:5226
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
